from enum import Enum


class CLICommand(Enum):
    ADD_CONTACT = "create_contact"
    DELETE_CONTACT = "delete_contact"
    FIND_CONTACT = "find_contact"
    FIND_CONTACT_BY_PHONE = "find_contact_by_phone"
    ADD_PHONE = "add_phone"
    EDIT_PHONE = "edit_phone"
    DELETE_PHONE = "delete_phone"
    SHOW_PHONE = "phone"
    SHOW_ALL = "show_all"
    ADD_BIRTHDAY = "add_birthday"
    SHOW_BIRTHDAY = "show_birthday"
    BIRTHDAYS = "birthdays"
    SHOW_NOTES = "show_notes"
    ADD_NOTE = "add_note"
    ADD_ADDRESS = "add_address"
    ADD_EMAIL = "add_email"
    EDIT_EMAIL = "edit_email"
    EXIT = "exit"
    CLOSE = "close"
    HELLO = "hello"
    EDIT_NAME = "edit_name"
    EDIT_ADDRESS = "edit_address"
    DELETE_ADDRESS = "delete_address"
